"""Declarative keyboard action bindings supporting HTMX triggers and JS callbacks."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/actions.ipynb.

# %% ../../nbs/core/actions.ipynb #a7ec2c3c
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .key_mapping import format_key_combo

# %% auto #0
__all__ = ['KeyAction']

# %% ../../nbs/core/actions.ipynb #0cc2fa99
@dataclass
class KeyAction:
    """A keyboard shortcut binding."""

    # Trigger
    key: str  # JavaScript key name (e.g., "Enter", " ", "ArrowUp")
    modifiers: frozenset[str] = field(
        default_factory=frozenset
    )  # required modifiers ("shift", "ctrl", "alt", "meta")

    # Action - exactly one should typically be set
    htmx_trigger: Optional[str] = None  # ID of hidden button to click
    js_callback: Optional[str] = None  # JS function name to call
    mode_enter: Optional[str] = None  # mode name to enter
    mode_exit: bool = False  # exit current mode (return to default)

    # Behavior
    prevent_default: bool = True  # call e.preventDefault()
    stop_propagation: bool = False  # call e.stopPropagation()

    # Conditions
    zone_ids: Optional[tuple[str, ...]] = None  # only in these zones (None = all)
    mode_names: Optional[tuple[str, ...]] = None  # only in these modes (None = all)
    not_modes: Optional[tuple[str, ...]] = None  # not in these modes
    custom_condition: Optional[str] = None  # raw JS expression for additional conditions

    # Documentation
    description: str = ""  # human-readable description for hints
    hint_group: str = "General"  # grouping for keyboard hints display
    show_in_hints: bool = True  # whether to show in keyboard hints

    def matches_context(
        self,
        zone_id: str,  # current active zone
        mode_name: str  # current mode
    ) -> bool:         # True if action is valid in this context
        """Check if action is valid for given zone and mode."""
        # Check zone condition
        if self.zone_ids is not None and zone_id not in self.zone_ids:
            return False
        
        # Check mode condition
        if self.mode_names is not None and mode_name not in self.mode_names:
            return False
        
        # Check not_modes condition
        if self.not_modes is not None and mode_name in self.not_modes:
            return False
        
        return True

    def get_display_key(self) -> str: # formatted key combo for display
        """Get formatted key combination for display."""
        return format_key_combo(self.key, self.modifiers)

    def to_js_config(self) -> dict: # JavaScript-compatible configuration
        """Convert to JavaScript configuration object."""
        return {
            "key": self.key,
            "modifiers": list(self.modifiers),
            "htmxTrigger": self.htmx_trigger,
            "jsCallback": self.js_callback,
            "modeEnter": self.mode_enter,
            "modeExit": self.mode_exit,
            "preventDefault": self.prevent_default,
            "stopPropagation": self.stop_propagation,
            "zoneIds": list(self.zone_ids) if self.zone_ids else None,
            "modeNames": list(self.mode_names) if self.mode_names else None,
            "notModes": list(self.not_modes) if self.not_modes else None,
            "customCondition": self.custom_condition,
            "description": self.description,
            "hintGroup": self.hint_group,
        }
