"""Configuration for focusable containers with navigable items."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/focus_zone.ipynb.

# %% ../../nbs/core/focus_zone.ipynb #2d5a1204
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional, Union

from cjm_fasthtml_keyboard_navigation.core.navigation import (
    NavigationPattern,
    LinearVertical
)

from cjm_fasthtml_tailwind.utilities.effects import ring, inset_ring
from cjm_fasthtml_daisyui.utilities.semantic_colors import ring_dui

# %% auto #0
__all__ = ['FocusZone']

# %% ../../nbs/core/focus_zone.ipynb #0f1c1acb
@dataclass
class FocusZone:
    """A focusable container with navigable items."""
    
    # Identity
    id: str  # HTML element ID of the container
    label: Optional[str] = None  # human-readable label for keyboard-hints display (falls back to id when None)

    # Item selection
    item_selector: Optional[str] = None  # CSS selector for items (None = scroll only)

    # Navigation
    navigation: Union[NavigationPattern, LinearVertical] = field(
        default_factory=LinearVertical
    )  # navigation pattern for this zone
    navigation_throttle_ms: int = 0  # minimum ms between navigation events (0 = no throttle)

    # Visual feedback - item focus
    item_focus_classes: tuple[str, ...] = (str(ring(2)), str(ring_dui.primary))  # CSS classes for focused item
    item_focus_attribute: str = "data-focused"  # attribute set to "true" on focused item

    # Visual feedback - zone focus (when zone is active)
    zone_focus_classes: tuple[str, ...] = (
        str(ring(2)), str(ring_dui.primary), str(inset_ring(2))
    )  # CSS classes for active zone container

    # Data extraction (for HTMX hidden inputs)
    data_attributes: tuple[str, ...] = ()  # data attributes to extract from focused item

    # Callbacks (JS function names)
    on_focus_change: Optional[str] = None  # called when focused item changes
    on_navigate: Optional[str] = None  # called on any navigation (for side effects like audition)
    on_zone_enter: Optional[str] = None  # called when zone becomes active
    on_zone_leave: Optional[str] = None  # called when zone loses focus

    # Child-activation wiring (used by ZoneManager.activate_keys — Enter/Space by default).
    # Exactly one path should typically be set; callback takes precedence if both are.
    # When neither is set, the zone has no child-activation behavior and no hint emits.
    activate_child_id: Optional[str] = None  # system_id of the child to activate (declarative path)
    activate_child_callback: Optional[str] = None  # JS function name (takes precedence over activate_child_id)
    activate_description: Optional[str] = None  # per-zone hint text (e.g., "Activate browser"); None = use manager default

    # Scroll behavior
    scroll_behavior: str = "smooth"  # "smooth" or "auto"
    scroll_block: str = "nearest"  # "start", "center", "end", "nearest"

    # HTMX integration
    hidden_input_prefix: str = ""  # prefix for auto-generated hidden input IDs

    # Initial state
    initial_index: int = 0  # initial focused item index

    def has_items(self) -> bool: # True if zone has selectable items
        """Check if zone has selectable items."""
        return self.item_selector is not None

    def has_activation(self) -> bool: # True if zone has child-activation wiring
        """Check if the zone has child-activation wiring (declarative or callback).
        
        Used by the hints renderer to decide whether to emit an "Activate panel"
        row, and by the JS dispatcher to know whether to attempt activation on
        the manager's activate_keys. Equivalent to
        `activate_child_id is not None or activate_child_callback is not None`.
        """
        return self.activate_child_id is not None or self.activate_child_callback is not None

    def get_display_label(self) -> str: # human-readable label, falling back to id
        """Get the label for keyboard-hints display, falling back to id when label is None."""
        return self.label if self.label is not None else self.id

    def get_hidden_input_id(
        self,
        attr: str  # the data attribute name
    ) -> str:      # the hidden input element ID
        """Get the hidden input ID for a data attribute."""
        prefix = self.hidden_input_prefix or self.id
        return f"{prefix}-{attr}"

    def to_js_config(self) -> dict: # JavaScript-compatible configuration
        """Convert to JavaScript configuration object."""
        return {
            "id": self.id,
            "itemSelector": self.item_selector,
            "navigationPattern": self.navigation.name,
            "navigationThrottleMs": self.navigation_throttle_ms,
            "itemFocusClasses": list(self.item_focus_classes),
            "itemFocusAttribute": self.item_focus_attribute,
            "zoneFocusClasses": list(self.zone_focus_classes),
            "dataAttributes": list(self.data_attributes),
            "hiddenInputPrefix": self.hidden_input_prefix or self.id,
            "onFocusChange": self.on_focus_change,
            "onNavigate": self.on_navigate,
            "onZoneEnter": self.on_zone_enter,
            "onZoneLeave": self.on_zone_leave,
            "activateChildId": self.activate_child_id,
            "activateChildCallback": self.activate_child_callback,
            "scrollBehavior": self.scroll_behavior,
            "scrollBlock": self.scroll_block,
            "initialIndex": self.initial_index,
        }
