"""Configurable key-to-direction mappings for customizable navigation keys."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/key_mapping.ipynb.

# %% ../../nbs/core/key_mapping.ipynb #6863af3b
from __future__ import annotations
from dataclasses import dataclass, field

# %% auto #0
__all__ = ['ARROW_KEYS', 'WASD_KEYS', 'VIM_KEYS', 'NUMPAD_KEYS', 'ARROWS_AND_WASD', 'ARROWS_AND_VIM', 'KEY_DISPLAY_MAP',
           'KeyMapping', 'format_key_for_display', 'format_key_combo']

# %% ../../nbs/core/key_mapping.ipynb #6fb8bdec
@dataclass(frozen=True)
class KeyMapping:
    """Maps physical keys to navigation directions."""
    up: tuple[str, ...] = ("ArrowUp",)    # keys that trigger "up" direction
    down: tuple[str, ...] = ("ArrowDown",) # keys that trigger "down" direction
    left: tuple[str, ...] = ("ArrowLeft",) # keys that trigger "left" direction
    right: tuple[str, ...] = ("ArrowRight",) # keys that trigger "right" direction

    def get_direction(
        self,
        key: str  # the pressed key (e.g., "ArrowUp", "w")
    ) -> str | None: # the direction ("up", "down", "left", "right") or None
        """Get direction for a given key press."""
        if key in self.up:
            return "up"
        elif key in self.down:
            return "down"
        elif key in self.left:
            return "left"
        elif key in self.right:
            return "right"
        return None

    def all_keys(self) -> tuple[str, ...]: # all mapped keys
        """Return all mapped keys."""
        return self.up + self.down + self.left + self.right

    def to_js_map(self) -> dict[str, str]: # {key: direction} mapping
        """Convert to JavaScript-compatible key-to-direction map."""
        result = {}
        for key in self.up:
            result[key] = "up"
        for key in self.down:
            result[key] = "down"
        for key in self.left:
            result[key] = "left"
        for key in self.right:
            result[key] = "right"
        return result

# %% ../../nbs/core/key_mapping.ipynb #7652b826
ARROW_KEYS = KeyMapping(
    up=("ArrowUp",),
    down=("ArrowDown",),
    left=("ArrowLeft",),
    right=("ArrowRight",)
)

# %% ../../nbs/core/key_mapping.ipynb #dc42e932
WASD_KEYS = KeyMapping(
    up=("w", "W"),
    down=("s", "S"),
    left=("a", "A"),
    right=("d", "D")
)

# %% ../../nbs/core/key_mapping.ipynb #911b59ae
VIM_KEYS = KeyMapping(
    up=("k",),
    down=("j",),
    left=("h",),
    right=("l",)
)

# %% ../../nbs/core/key_mapping.ipynb #7c9970f4
NUMPAD_KEYS = KeyMapping(
    up=("8",),
    down=("2",),
    left=("4",),
    right=("6",)
)

# %% ../../nbs/core/key_mapping.ipynb #1cfef8ac
ARROWS_AND_WASD = KeyMapping(
    up=("ArrowUp", "w", "W"),
    down=("ArrowDown", "s", "S"),
    left=("ArrowLeft", "a", "A"),
    right=("ArrowRight", "d", "D")
)

# %% ../../nbs/core/key_mapping.ipynb #3db2d2df
ARROWS_AND_VIM = KeyMapping(
    up=("ArrowUp", "k"),
    down=("ArrowDown", "j"),
    left=("ArrowLeft", "h"),
    right=("ArrowRight", "l")
)

# %% ../../nbs/core/key_mapping.ipynb #4f2e487f
KEY_DISPLAY_MAP: dict[str, str] = {
    "ArrowUp": "↑",
    "ArrowDown": "↓",
    "ArrowLeft": "←",
    "ArrowRight": "→",
    " ": "Space",
    "Delete": "Del",
    "Backspace": "Bksp",
    "Escape": "Esc",
    "Enter": "Enter",
    "Tab": "Tab",
    "Control": "Ctrl",
    "Shift": "Shift",
    "Alt": "Alt",
    "Meta": "Cmd",
}

# %% ../../nbs/core/key_mapping.ipynb #ff56157b
def format_key_for_display(
    key: str  # the JavaScript key name
) -> str:     # human-readable display string
    """Format a key name for user display."""
    return KEY_DISPLAY_MAP.get(key, key)

# %% ../../nbs/core/key_mapping.ipynb #6c666a8b
def format_key_combo(
    key: str,                        # the main key
    modifiers: frozenset[str] = frozenset() # modifier keys (shift, ctrl, alt, meta)
) -> str:                            # formatted string like "Ctrl+Shift+A"
    """Format a key combination for display."""
    parts = []
    # Order: Ctrl, Alt, Shift, Meta
    if "ctrl" in modifiers:
        parts.append("Ctrl")
    if "alt" in modifiers:
        parts.append("Alt")
    if "shift" in modifiers:
        parts.append("Shift")
    if "meta" in modifiers:
        parts.append("Cmd")
    parts.append(format_key_for_display(key))
    return "+".join(parts)
