"""Configuration for keyboard modes that change navigation and action behavior."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/modes.ipynb.

# %% ../../nbs/core/modes.ipynb #c50275bc
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional, Union

from .navigation import NavigationPattern

# %% auto #0
__all__ = ['NAVIGATION_MODE', 'KeyboardMode']

# %% ../../nbs/core/modes.ipynb #f9eaa16a
@dataclass
class KeyboardMode:
    """A named mode that changes keyboard behavior."""

    # Identity
    name: str  # unique mode name (e.g., "navigation", "split", "audition")

    # Entry/exit keys
    enter_key: Optional[str] = None  # key to enter mode (None = programmatic only)
    enter_modifiers: frozenset[str] = field(
        default_factory=frozenset
    )  # modifiers required with enter_key
    exit_key: str = "Escape"  # key to exit mode
    exit_modifiers: frozenset[str] = field(
        default_factory=frozenset
    )  # modifiers required with exit_key

    # Conditions
    zone_ids: Optional[tuple[str, ...]] = None  # only available in these zones (None = all)

    # Behavior overrides
    navigation_override: Optional[NavigationPattern] = None  # override zone's navigation pattern

    # Callbacks (JS function names)
    on_enter: Optional[str] = None  # called when entering mode
    on_exit: Optional[str] = None  # called when exiting mode

    # Visual indicator
    indicator_text: Optional[str] = None  # text shown in UI when mode is active

    # Auto-exit conditions
    exit_on_zone_change: bool = True  # exit mode when switching zones

    def is_available_in_zone(
        self,
        zone_id: str  # the zone to check
    ) -> bool:        # True if mode is available in zone
        """Check if mode is available in given zone."""
        if self.zone_ids is None:
            return True
        return zone_id in self.zone_ids

    def to_js_config(self) -> dict: # JavaScript-compatible configuration
        """Convert to JavaScript configuration object."""
        return {
            "name": self.name,
            "enterKey": self.enter_key,
            "enterModifiers": list(self.enter_modifiers),
            "exitKey": self.exit_key,
            "exitModifiers": list(self.exit_modifiers),
            "zoneIds": list(self.zone_ids) if self.zone_ids else None,
            "navigationOverride": (
                self.navigation_override.name 
                if self.navigation_override else None
            ),
            "onEnter": self.on_enter,
            "onExit": self.on_exit,
            "indicatorText": self.indicator_text,
            "exitOnZoneChange": self.exit_on_zone_change,
        }

# %% ../../nbs/core/modes.ipynb #e6feea64
NAVIGATION_MODE = KeyboardMode(
    name="navigation",
    enter_key=None,  # default mode, cannot be entered via key
    exit_key="",     # cannot be exited (it's the default)
    indicator_text=None,
    exit_on_zone_change=False  # default mode persists across zone changes
)
