"""Core JavaScript utility generators for keyboard navigation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/js/utils.ipynb.

# %% ../../nbs/js/utils.ipynb #be1ce6b4
from __future__ import annotations
import json
from typing import Any

# %% auto #0
__all__ = ['js_config_from_dict', 'js_input_detection', 'js_focus_ring_helpers', 'js_scroll_into_view', 'js_hidden_input_update',
           'js_trigger_click', 'js_get_data_attributes', 'js_get_modifiers', 'js_all_utils']

# %% ../../nbs/js/utils.ipynb #3781a4db
def js_config_from_dict(
    config: dict[str, Any],  # Python dict to convert
    var_name: str = "cfg"    # JavaScript variable name
) -> str:                    # JavaScript const declaration
    """Generate JavaScript const declaration from Python dict."""
    json_str = json.dumps(config, indent=2)
    return f"const {var_name} = {json_str};"

# %% ../../nbs/js/utils.ipynb #b1173d3d
def js_input_detection(
    selector: str = "input, textarea, select, [contenteditable='true']"  # CSS selector for input elements
) -> str:  # JavaScript function definition
    """Generate JavaScript function to detect if input element is focused."""
    # Escape single quotes for JavaScript string
    escaped_selector = selector.replace("'", "\\'")
    return f'''
function isInputFocused(target) {{
    return target && target.matches && target.matches('{escaped_selector}');
}}
'''.strip()

# %% ../../nbs/js/utils.ipynb #f69c33de
def js_focus_ring_helpers(
    default_classes: tuple[str, ...] = ("ring-2", "ring-primary")  # default focus ring CSS classes
) -> str:  # JavaScript function definitions
    """Generate JavaScript functions for adding/removing focus ring classes."""
    default_list = json.dumps(list(default_classes))
    return f'''
const DEFAULT_FOCUS_CLASSES = {default_list};

function addFocusRing(element, classes = DEFAULT_FOCUS_CLASSES) {{
    if (!element) return;
    classes.forEach(cls => element.classList.add(cls));
}}

function removeFocusRing(element, classes = DEFAULT_FOCUS_CLASSES) {{
    if (!element) return;
    classes.forEach(cls => element.classList.remove(cls));
}}
'''.strip()

# %% ../../nbs/js/utils.ipynb #93c9edc5
def js_scroll_into_view(
    behavior: str = "smooth",  # "smooth" or "auto"
    block: str = "nearest"     # "start", "center", "end", "nearest"
) -> str:  # JavaScript function definition
    """Generate JavaScript function to scroll element into view."""
    return f'''
function scrollToElement(element, options = {{}}) {{
    if (!element) return;
    element.scrollIntoView({{
        behavior: options.behavior || '{behavior}',
        block: options.block || '{block}'
    }});
}}
'''.strip()

# %% ../../nbs/js/utils.ipynb #e492f90f
def js_hidden_input_update() -> str: # JavaScript function definition
    """Generate JavaScript function to update hidden input values."""
    return '''
function updateHiddenInput(inputId, value) {
    const input = document.getElementById(inputId);
    if (input) {
        input.value = value || '';
    }
}

function updateHiddenInputs(updates) {
    for (const [inputId, value] of Object.entries(updates)) {
        updateHiddenInput(inputId, value);
    }
}
'''.strip()

# %% ../../nbs/js/utils.ipynb #d7188749
def js_trigger_click() -> str: # JavaScript function definition
    """Generate JavaScript function to programmatically click a button."""
    return '''
function triggerClick(buttonId) {
    const button = document.getElementById(buttonId);
    if (button) {
        button.click();
    }
}
'''.strip()

# %% ../../nbs/js/utils.ipynb #882d2143
def js_get_data_attributes() -> str: # JavaScript function definition
    """Generate JavaScript function to extract data attributes from element."""
    return '''
function getDataAttributes(element, attributeNames) {
    if (!element) return {};
    const result = {};
    for (const attr of attributeNames) {
        const dataAttr = 'data-' + attr;
        result[attr] = element.getAttribute(dataAttr) || '';
    }
    return result;
}
'''.strip()

# %% ../../nbs/js/utils.ipynb #2fa313b2
def js_get_modifiers() -> str: # JavaScript function definition
    """Generate JavaScript function to extract modifier keys from event."""
    return '''
function getModifiers(event) {
    const mods = new Set();
    if (event.shiftKey) mods.add('shift');
    if (event.ctrlKey) mods.add('ctrl');
    if (event.altKey) mods.add('alt');
    if (event.metaKey) mods.add('meta');
    return mods;
}

function modifiersMatch(eventMods, requiredMods) {
    if (requiredMods.length === 0 && eventMods.size === 0) return true;
    if (requiredMods.length !== eventMods.size) return false;
    for (const mod of requiredMods) {
        if (!eventMods.has(mod)) return false;
    }
    return true;
}
'''.strip()

# %% ../../nbs/js/utils.ipynb #46da251f
def js_all_utils(
    input_selector: str = "input, textarea, select, [contenteditable='true']",  # input element selector
    default_focus_classes: tuple[str, ...] = ("ring-2", "ring-primary"),  # focus ring classes
    scroll_behavior: str = "smooth",  # scroll behavior
    scroll_block: str = "nearest"     # scroll block alignment
) -> str:  # all utility functions combined
    """Generate all JavaScript utility functions."""
    parts = [
        "// === Utility Functions ===",
        js_input_detection(input_selector),
        js_focus_ring_helpers(default_focus_classes),
        js_scroll_into_view(scroll_behavior, scroll_block),
        js_hidden_input_update(),
        js_trigger_click(),
        js_get_data_attributes(),
        js_get_modifiers(),
    ]
    return "\n\n".join(parts)
