"""Components for displaying keyboard shortcut hints to users.

Docs: https://cj-mills.github.io/cjm-fasthtml-keyboard-navigationcomponents/hints.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/hints.ipynb.

# %% ../../nbs/components/hints.ipynb #e5043c09
from __future__ import annotations
from collections import defaultdict
from typing import Optional, Union
from fasthtml.common import Div, Span, FT

from ..core.actions import KeyAction
from ..core.manager import ZoneManager
from ..core.key_mapping import format_key_for_display

from cjm_fasthtml_daisyui.components.data_display.badge import badge, badge_colors, badge_styles
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_wrap, gap, items
)
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_family, font_weight
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Design system recipes (V11 icon-size roles)
from cjm_fasthtml_design_system.icons import icons

# %% auto #0
__all__ = ['NAV_ICON_MAP', 'KEY_ICON_MAP', 'get_key_icon', 'render_hint_badge', 'create_nav_icon_hint',
           'create_modifier_key_hint', 'render_hint_group', 'group_actions_by_hint_group',
           'group_actions_by_zone_and_hint_group', 'mode_context_label', 'derive_navigation_hints',
           'derive_hierarchy_hints', 'derive_mode_exit_hints', 'render_hints_from_actions', 'render_keyboard_hints']

# %% ../../nbs/components/hints.ipynb #1680f700
# Icon mappings for navigation patterns and common keys
NAV_ICON_MAP = {
    "up_down": "arrow-down-up",
    "left_right": "arrow-left-right",
}

KEY_ICON_MAP = {
    "shift": "arrow-big-up",
    "delete": "trash-2",
    "del": "trash-2",
    "enter": "corner-down-left",
    "return": "corner-down-left",
    "backspace": "delete",
    "bksp": "delete",
    "escape": "x",
    "esc": "x",
}


def get_key_icon(
    key_name: str,                      # key name to look up (case-insensitive)
    size: int = icons.dense_inline      # icon size (V11 dense_inline role)
) -> FT | None:                         # icon component or None if no icon mapping
    """Get a lucide icon for a key name, if one exists."""
    icon_name = KEY_ICON_MAP.get(key_name.lower())
    if icon_name:
        return lucide_icon(icon_name, size=size)
    return None


def render_hint_badge(
    key_display: Union[str, FT],  # formatted key string or icon component
    description: str,              # action description
    style: str = "ghost",          # badge style (ghost, outline, soft, dash)
    auto_icon: bool = False        # auto-convert known keys to icons
) -> Div:                          # hint badge component
    """Render a single keyboard hint as a badge."""
    badge_style = getattr(badge_styles, style, badge_styles.ghost)
    
    # Handle key display
    if isinstance(key_display, str):
        # Try to auto-convert to icon if enabled
        if auto_icon:
            icon = get_key_icon(key_display)
            if icon:
                key_component = icon
            else:
                key_component = Span(key_display, cls=combine_classes(font_family.mono, font_weight.bold))
        else:
            key_component = Span(key_display, cls=combine_classes(font_family.mono, font_weight.bold))
    else:
        key_component = key_display
    
    return Div(
        key_component,
        Span(description, cls=m.l(1)),
        cls=combine_classes(badge, badge_style, flex_display, items.center, gap(1))
    )


def create_nav_icon_hint(
    icon_name: str,      # lucide icon name (e.g., "arrow-down-up")
    description: str,    # action description
    style: str = "ghost" # badge style
) -> Div:                # hint badge with icon
    """Create a hint badge with a lucide icon."""
    icon = lucide_icon(icon_name, size=icons.dense_inline)
    return render_hint_badge(icon, description, style)


def create_modifier_key_hint(
    modifier: str,       # modifier key name (e.g., "shift", "ctrl")
    key_icon_or_text: Union[str, FT],  # the main key icon or text
    description: str,    # action description
    style: str = "ghost" # badge style
) -> Div:                # hint badge with modifier + key
    """Create a hint badge with a modifier key and main key."""
    badge_style = getattr(badge_styles, style, badge_styles.ghost)
    
    # Get modifier icon if available
    mod_icon = get_key_icon(modifier)
    mod_component = mod_icon if mod_icon else Span(modifier.capitalize(), cls=font_weight.bold)
    
    # Handle main key
    if isinstance(key_icon_or_text, str):
        main_icon = get_key_icon(key_icon_or_text)
        if main_icon:
            key_component = main_icon
        else:
            key_component = Span(key_icon_or_text, cls=combine_classes(font_family.mono, font_weight.bold))
    else:
        key_component = key_icon_or_text
    
    return Div(
        mod_component,
        key_component,
        Span(description, cls=m.l(1)),
        cls=combine_classes(badge, badge_style, flex_display, items.center, gap(1))
    )

# %% ../../nbs/components/hints.ipynb #01d4eef5
def render_hint_group(
    group_name: str,         # group header text
    hints: list[tuple[str, str]],  # list of (key_display, description) tuples
    badge_style: str = "ghost"     # badge style for this group
) -> Div:                    # group container with header and hints
    """Render a group of related keyboard hints."""
    badges = [render_hint_badge(key, desc, badge_style) for key, desc in hints]
    
    return Div(
        Span(
            group_name,
            cls=combine_classes(font_size.xs, font_weight.semibold, m.r(2))
        ),
        *badges,
        cls=combine_classes(flex_display, items.center, gap(1), flex_wrap.wrap)
    )

# %% ../../nbs/components/hints.ipynb #951c0d24
def group_actions_by_hint_group(
    actions: tuple[KeyAction, ...]  # actions to group
) -> dict[str, list[KeyAction]]:    # grouped actions
    """Group actions by their hint_group attribute."""
    groups = defaultdict(list)
    for action in actions:
        if action.show_in_hints and action.description:
            groups[action.hint_group].append(action)
    return dict(groups)

# %% ../../nbs/components/hints.ipynb #bdee9bda
def group_actions_by_zone_and_hint_group(
    manager: ZoneManager,  # the zone manager whose actions to group
) -> list[tuple[Optional[str], str, list[KeyAction]]]:  # ordered (zone_label_or_None, hint_group, actions) tuples
    """Group actions for hint display, scoped by zone and hint_group.

    Returns an ordered list of (zone_label, hint_group, actions) tuples:

    - **Shared section** (zone_label=None) appears FIRST, containing actions
      with zone_ids=None (truly global) or zone_ids covering all zones in the
      manager. Single-zone managers route all actions through this section,
      preserving single-zone consumer rendering (no zone-label prefix).
    - **Per-zone sections** follow, in the order zones are declared on the
      manager. zone_label is FocusZone.get_display_label() (label, falling
      back to id). Actions with zone_ids matching exactly one zone land here.
    - **Within each section**, hint_groups appear in insertion (first-seen)
      order. Actions are emitted in their original tuple order.

    Actions with show_in_hints=False or empty description are excluded.

    Edge cases:
    - Multi-zone partial coverage (zone_ids touches >1 zone but not all):
      routed to shared. Rare in practice; documents the action as shared.
    - zone_ids referencing a zone not in manager.zones: silently dropped.
    """
    zone_id_order = [zone.id for zone in manager.zones]
    zone_labels = {zone.id: zone.get_display_label() for zone in manager.zones}
    all_zone_ids = set(zone_id_order)

    # Partition actions: shared vs per-zone, preserving hint_group insertion order
    shared_groups: dict[str, list[KeyAction]] = defaultdict(list)
    per_zone_groups: dict[str, dict[str, list[KeyAction]]] = {
        zone_id: defaultdict(list) for zone_id in zone_id_order
    }

    for action in manager.actions:
        if not action.show_in_hints or not action.description:
            continue

        if action.zone_ids is None or set(action.zone_ids) >= all_zone_ids:
            # Unrestricted or covers all zones -> shared section
            shared_groups[action.hint_group].append(action)
        elif len(action.zone_ids) == 1 and action.zone_ids[0] in zone_labels:
            # Scoped to one zone -> per-zone section
            per_zone_groups[action.zone_ids[0]][action.hint_group].append(action)
        elif any(zid in zone_labels for zid in action.zone_ids):
            # Multi-zone partial coverage -> shared (rare edge case)
            shared_groups[action.hint_group].append(action)
        # else: zone_ids references no registered zone -> silently dropped

    # Build ordered result: shared first, then per-zone in declaration order
    result: list[tuple[Optional[str], str, list[KeyAction]]] = []
    for group_name, actions in shared_groups.items():
        result.append((None, group_name, actions))
    for zone_id in zone_id_order:
        for group_name, actions in per_zone_groups[zone_id].items():
            result.append((zone_labels[zone_id], group_name, actions))

    return result


def mode_context_label(
    action: KeyAction,  # action whose mode constraints to summarize
) -> Optional[str]:     # short chip-friendly label, or None for unrestricted actions
    """Derive a short mode-context label from a KeyAction's mode constraints.

    Returns None when the action has no mode restrictions (works in any mode —
    no chip should render). Returns the mode name(s) when mode_names is set.
    Returns 'default' when not_modes is set (action is excluded from specified
    modes, so it fires in the default mode).

    Examples:
        mode_names=("split",)             -> "split"
        mode_names=("token-select",)      -> "token-select"
        mode_names=("split", "edit")      -> "split + edit"
        not_modes=("split",)              -> "default"
        no mode constraints               -> None
    """
    if action.mode_names:
        return " + ".join(action.mode_names)
    if action.not_modes:
        return "default"
    return None

# %% ../../nbs/components/hints.ipynb #cb2d3361
def derive_navigation_hints(
    manager: ZoneManager,  # the zone manager whose navigation to derive hints from
) -> list[tuple[str, str]]:  # ordered (display_key, description) tuples
    """Derive built-in navigation hint rows from manager.key_mapping + zone patterns.

    Walks every zone with `has_items()` true, unions the navigable directions
    via each zone's `navigation.get_supported_directions()`, and emits hint
    rows using the actual keys from `manager.key_mapping`. Replaces the
    earlier hardcoded `↑/↓ Navigate items` row, which was wrong under custom
    key_mappings (wasd, vim, etc.).

    Returns rows for each direction pair (up/down, left/right) whose keys are
    *actually* bound and *actually* used by some zone:

    - **Vertical pair** (up/down): emitted when any zone has a pattern that
      supports up/down navigation. Display uses `key_mapping.up[0]` /
      `key_mapping.down[0]`.
    - **Horizontal pair** (left/right): emitted when any zone supports
      left/right navigation, UNLESS the in-zone horizontal keys collide with
      the manager's zone-switch keys (prev_zone_key/next_zone_key). In that
      case the zone-switch row already documents those keys; emitting a
      second row would be misleading (the zone-switch path wins at runtime).

    Returns an empty list when no zone supports key-based navigation (e.g.,
    all zones are ScrollOnly, or no zone has an item_selector).
    """
    directions_used = set()
    for zone in manager.zones:
        if not zone.has_items():
            continue
        # Each NavigationPattern self-reports its supported directions —
        # change-tolerant if new patterns are added (e.g., a future 2D grid
        # variant doesn't need this function updated).
        get_dirs = getattr(zone.navigation, "get_supported_directions", None)
        if get_dirs is not None:
            directions_used.update(get_dirs())

    if not directions_used:
        return []

    km = manager.key_mapping
    multi_zone = len(manager.zones) > 1
    hints: list[tuple[str, str]] = []

    # Vertical pair (up/down)
    if {"up", "down"} <= directions_used and km.up and km.down:
        hints.append((
            f"{format_key_for_display(km.up[0])} / {format_key_for_display(km.down[0])}",
            "Navigate items",
        ))

    # Horizontal pair (left/right) — skip when keys collide with zone-switch
    if {"left", "right"} <= directions_used and km.left and km.right:
        left_collides = multi_zone and km.left[0] == manager.prev_zone_key
        right_collides = multi_zone and km.right[0] == manager.next_zone_key
        if not (left_collides and right_collides):
            hints.append((
                f"{format_key_for_display(km.left[0])} / {format_key_for_display(km.right[0])}",
                "Navigate items",
            ))

    return hints

# %% ../../nbs/components/hints.ipynb #a4b36224
def derive_hierarchy_hints(
    manager: ZoneManager,        # the zone manager whose hierarchy keys to surface
    *,
    is_child: bool = False,      # True when this manager is rendered as a child in a hierarchical hints modal
) -> list[tuple[str, str]]:      # ordered (display_key, description) rows; fold into manager-derived Navigation group
    """Derive built-in hierarchy-key hint rows: Esc deactivation + Enter/Space activation.

    These keys are baked into the JS dispatcher (`js_keyboard_handler` in
    `generators.py`), not declared as `KeyAction`s — so a renderer iterating
    only `manager.actions` would miss them. This helper bridges that gap, analogous
    to `derive_navigation_hints` for navigation keys.

    Returns rows that fold into the manager-derived "Navigation" group (callers
    extend `nav_rows` with the result before emitting `_render_modal_group`).

    Emission rules:

    - **Escape — Deactivate panel** is emitted only when `is_child=True`. The JS
      dispatcher's Escape→deactivate-child branch fires when the manager has a
      parent in the coordinator hierarchy at runtime; the renderer can't know
      parent state at render time, but the modal's *multi-manager mode*
      (`child_managers=[...]`) is the canonical signal that a given manager IS a
      child in the hierarchy being documented. Callers pass `is_child=True` for
      every entry in `child_managers`.

    - **Enter / Space — Activate panel** is emitted when the manager has at
      least one zone with activation wiring (`activate_child_id` or
      `activate_child_callback`) AND `manager.activate_keys` is non-empty.
      The description defaults to `manager.activate_description` ("Activate
      panel"); consumers override at the manager level for site-specific text.
      Empty `activate_keys` opts out entirely (no row emitted).

    The hierarchy demo's on-page legend has long listed both keys; this helper
    is what lets the same information land in the modal too.
    """
    rows: list[tuple[str, str]] = []

    if is_child:
        rows.append((format_key_for_display("Escape"), "Deactivate panel, return to parent"))

    if manager.activate_keys and manager.has_activatable_zone():
        key_display = " / ".join(format_key_for_display(k) for k in manager.activate_keys)
        rows.append((key_display, manager.activate_description))

    return rows


def derive_mode_exit_hints(
    manager: ZoneManager,                          # the zone manager whose mode exit keys to surface
) -> list[tuple[str, str, Optional[str]]]:         # ordered (display_key, description, mode_name) rows; mode_name drives the V13 mode chip
    """Derive built-in mode-exit hint rows for every non-default mode that defines an exit_key.

    Mode exit is handled by the JS dispatcher (`js_keyboard_handler`'s
    `currentModeConfig.exitKey === key` branch at `generators.py`) when a mode
    has a non-empty `exit_key`. Like Escape-deactivate-child, this is not a
    declared `KeyAction` — so the renderer needs a derivation seam.

    Returned rows include the mode_name as the third tuple element. The modal
    renderer uses this to attach the V13 mode chip ("split", "edit", etc.) to
    the row, so the user sees the row is only meaningful while in that mode.

    Honors `mode.exit_modifiers` via `format_key_combo` so chord exits like
    Ctrl+Escape display correctly. Modes with empty `exit_key` (e.g., the
    implicit `NAVIGATION_MODE` whose exit_key is `""`) are skipped silently.
    """
    from cjm_fasthtml_keyboard_navigation.core.key_mapping import format_key_combo

    rows: list[tuple[str, str, Optional[str]]] = []
    for mode in manager.modes:
        if not mode.exit_key:
            continue
        # exit_modifiers is frozenset[str]; format_key_combo handles both empty and populated cases.
        display_key = format_key_combo(mode.exit_key, mode.exit_modifiers)
        rows.append((display_key, "Exit mode", mode.name))
    return rows

# %% ../../nbs/components/hints.ipynb #471f86ab
def render_hints_from_actions(
    actions: tuple[KeyAction, ...],  # actions to display hints for
    badge_style: str = "ghost"       # badge style
) -> Div:                            # container with all hint groups
    """Render keyboard hints from action configurations."""
    groups = group_actions_by_hint_group(actions)
    
    group_components = []
    for group_name, group_actions in groups.items():
        hints = [(a.get_display_key(), a.description) for a in group_actions]
        group_components.append(
            render_hint_group(group_name, hints, badge_style)
        )
    
    return Div(
        *group_components,
        cls=combine_classes(flex_display, flex_wrap.wrap, gap(4))
    )

# %% ../../nbs/components/hints.ipynb #f3e153b5
def render_keyboard_hints(
    manager: ZoneManager,                      # the zone manager
    include_navigation: bool = True,           # include navigation hints
    include_zone_switch: bool = True,          # include zone switching hints
    badge_style: str = "ghost",                # badge style
    container_id: str = "kb-hints",            # container element ID
    use_icons: bool = True                     # use lucide icons for nav hints
) -> Div:                                      # complete hints component
    """Render complete keyboard hints for a zone manager."""
    from cjm_fasthtml_keyboard_navigation.core.key_mapping import format_key_for_display
    
    sections = []
    
    # Navigation hints
    if include_navigation:
        if use_icons:
            nav_badge = create_nav_icon_hint(NAV_ICON_MAP["up_down"], "Navigate", badge_style)
            sections.append(
                Div(
                    Span("Navigation", cls=combine_classes(font_size.xs, font_weight.semibold, m.r(2))),
                    nav_badge,
                    cls=combine_classes(flex_display, items.center, gap(1), flex_wrap.wrap)
                )
            )
        else:
            nav_hints = [("↑/↓", "Navigate")]
            sections.append(render_hint_group("Navigation", nav_hints, badge_style))
    
    # Zone switching hints
    if include_zone_switch and len(manager.zones) > 1:
        if use_icons:
            switch_badge = create_nav_icon_hint(NAV_ICON_MAP["left_right"], "Switch Panel", badge_style)
            sections.append(
                Div(
                    Span("Panels", cls=combine_classes(font_size.xs, font_weight.semibold, m.r(2))),
                    switch_badge,
                    cls=combine_classes(flex_display, items.center, gap(1), flex_wrap.wrap)
                )
            )
        else:
            prev_key = format_key_for_display(manager.prev_zone_key)
            next_key = format_key_for_display(manager.next_zone_key)
            switch_hints = [(f"{prev_key}/{next_key}", "Switch Panel")]
            sections.append(render_hint_group("Panels", switch_hints, badge_style))
    
    # Action hints (grouped by hint_group)
    action_hints = render_hints_from_actions(manager.actions, badge_style)
    sections.append(action_hints)
    
    return Div(
        *sections,
        id=container_id,
        cls=combine_classes(flex_display, flex_wrap.wrap, gap(4), font_size.sm)
    )
