"""Modal-based keyboard shortcut reference with scannable grouped layout and `?` key trigger."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/hints_modal.ipynb.

# %% ../../nbs/components/hints_modal.ipynb #hints-modal-imports
from __future__ import annotations
from typing import Optional, Sequence
from fasthtml.common import Div, Span, Dialog, Button, Form, H3, Kbd, Script, FT

from ..core.actions import KeyAction
from ..core.manager import ZoneManager
from cjm_fasthtml_keyboard_navigation.components.hints import (
    derive_navigation_hints,
    derive_hierarchy_hints,
    derive_mode_exit_hints,
    group_actions_by_zone_and_hint_group,
    mode_context_label,
)

from cjm_fasthtml_daisyui.components.actions.modal import modal, modal_box, modal_backdrop
from cjm_fasthtml_daisyui.components.actions.button import btn_modifiers
from cjm_fasthtml_daisyui.components.data_display.kbd import kbd as kbd_cls, kbd_sizes as kbd_sz
from cjm_fasthtml_daisyui.components.data_display.badge import badge, badge_styles, badge_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui, border_dui

from cjm_fasthtml_design_system.text_tiers import text_tiers

from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, max_w
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, items, gap, justify, flex_direction,
)
from cjm_fasthtml_tailwind.utilities.layout import position, right, top, columns, break_util
from cjm_fasthtml_tailwind.utilities.borders import border
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Design system recipes (V1 button roles, V11 icon-size roles)
from cjm_fasthtml_design_system.buttons import buttons
from cjm_fasthtml_design_system.icons import icons, IconSize

# %% auto #0
__all__ = ['render_keyboard_hints_trigger', 'render_keyboard_hints_modal']

# %% ../../nbs/components/hints_modal.ipynb #key-display
def _render_key_combo(
    display_key: str,  # formatted key combo string (e.g., "Ctrl+Shift+\u2191")
) -> Div:              # container with kbd elements for each key part
    """Render a key combination as a sequence of kbd elements joined by `+`."""
    parts = display_key.split('+')
    elements = []
    for i, part in enumerate(parts):
        if i > 0:
            elements.append(Span('+', cls=combine_classes(text_tiers.muted, m.x(0.5))))
        elements.append(Kbd(part.strip(), cls=combine_classes(kbd_cls, kbd_sz.sm)))
    return Div(*elements, cls=combine_classes(flex_display, items.center))

# %% ../../nbs/components/hints_modal.ipynb #hint-row-group
def _render_hint_row(
    display_key: str,                       # formatted key combo string
    description: str,                       # action description
    mode_label: Optional[str] = None,        # mode-context chip text (e.g., "split", "default"); None for no chip
) -> Div:                                    # single shortcut row with key, description, and optional mode chip
    """Render a single shortcut row: key combo on left, description (with optional mode chip) on right."""
    description_components = [Span(description, cls=combine_classes(text_tiers.secondary))]
    if mode_label is not None:
        description_components.append(
            Span(
                mode_label,
                cls=combine_classes(
                    badge, badge_styles.soft, badge_sizes.xs,
                    m.l(2),
                ),
            )
        )
    return Div(
        _render_key_combo(display_key),
        Div(
            *description_components,
            cls=combine_classes(flex_display, items.center),
        ),
        cls=combine_classes(
            flex_display, items.center, justify.between,
            gap(4), p.y(1),
        )
    )


def _render_modal_group(
    group_name: str,                                                   # group header text
    rows: list[tuple[str, str, Optional[str]]],                         # list of (display_key, description, mode_label)
) -> Div:                                                              # group container with header and rows
    """Render a group of related shortcuts with a header.

    `break_util.inside.avoid_column` keeps the entire group (header + rows)
    in one column inside the modal body's CSS-columns layout — groups never
    split across columns, preserving "form follows function" scannability.
    """
    row_elements = [_render_hint_row(key, desc, mode) for key, desc, mode in rows]
    return Div(
        Div(
            group_name,
            cls=combine_classes(
                font_size.xs, font_weight.semibold,
                text_tiers.muted,
                p.b(1),
                border.b(), border_dui.base_content.opacity(10),
                m.b(1),
            )
        ),
        *row_elements,
        cls=combine_classes(m.b(4), break_util.inside.avoid_column),
    )

# %% ../../nbs/components/hints_modal.ipynb #modal-body
def _render_section_header(
    label: str,  # human-readable section label
) -> Div:        # styled section-header element
    """Render a section header for one manager in a multi-manager modal.

    Visually distinct from group headers (`_render_modal_group`):
    - Section headers: font-sm + bold + secondary tier + top border + extra spacing
    - Group headers:   font-xs + semibold + muted tier + bottom border (no top)

    `break_util.after.avoid` keeps a section header attached to its first
    group inside the CSS-columns layout — prevents the orphan-header case where
    a header lands at the bottom of one column and its first group at the top
    of the next. (`break_util.inside.avoid_column` exists but only applies to
    breaks INSIDE the element; for "don't break right after", `break-after: avoid`
    is the correct CSS property.)
    """
    return Div(
        label,
        cls=combine_classes(
            font_size.sm, font_weight.bold,
            text_tiers.secondary,
            p.t(3), p.b(2),
            m.t(2), m.b(2),
            border.t(2), border_dui.base_content.opacity(20),
            break_util.after.avoid,
        ),
    )


# Built-in group label that the manager-derived Navigation rows render under.
# Consumer actions with `hint_group=_BUILTIN_NAV_GROUP` in the shared section
# get merged into the same group (no duplicate header).
_BUILTIN_NAV_GROUP = "Navigation"


def _render_manager_groups(
    manager: ZoneManager,                # the manager to render groups for
    include_zone_switch: bool = True,    # include zone-switch hint when multi-zone
    is_child: bool = False,              # True when this manager is rendered as a child in a hierarchical modal
) -> list[FT]:                           # flat list of group FT elements (no wrapping Div)
    """Render the keyboard-shortcut groups for a single ZoneManager.

    Composes:
    1. **Manager-derived "Navigation" group**: derived nav rows from
       `derive_navigation_hints(manager)` (via `manager.key_mapping` + each zone's
       `navigation.get_supported_directions()`), plus the Switch-panel row when
       `include_zone_switch=True` and multi-zone, **plus** library-baked
       hierarchy rows from `derive_hierarchy_hints(manager, is_child=is_child)`
       (Esc deactivate-child when is_child=True; Enter/Space activate-panel
       when the manager has activatable zones), **plus** library-baked
       mode-exit rows from `derive_mode_exit_hints(manager)` (each tagged
       with its mode chip so the user sees the row only applies in that mode).
       **Plus** any consumer actions whose `hint_group == "Navigation"` AND
       land in the shared section (zone_label=None) — they fold into the
       same group rather than rendering a duplicate "Navigation" header.
    2. **Zone-aware action groups**: from `group_actions_by_zone_and_hint_group`,
       with `"<zone label> — <hint_group>"` headers for per-zone sections and
       plain `"<hint_group>"` for shared sections (other than Navigation).

    Per-zone "Navigation" groups stay separate (they're zone-scoped — distinct
    from the manager-level Navigation row). Only the shared-section Navigation
    rows merge into the manager-derived group.

    Returned as a flat list (no wrapping Div) so callers can interleave section
    headers between groups when rendering multi-manager hierarchies.

    The `is_child` flag is set by `_render_modal_body` for every entry in
    `child_managers` — the canonical signal that a manager is a child in the
    hierarchy being documented. See `derive_hierarchy_hints` for the underlying
    emission rules.
    """
    from cjm_fasthtml_keyboard_navigation.core.key_mapping import format_key_for_display

    elements: list[FT] = []

    # Build the manager-derived "Navigation" group's rows
    nav_rows: list[tuple[str, str, Optional[str]]] = [
        (display_key, description, None)
        for display_key, description in derive_navigation_hints(manager)
    ]
    if include_zone_switch and len(manager.zones) > 1:
        prev_key = format_key_for_display(manager.prev_zone_key)
        next_key = format_key_for_display(manager.next_zone_key)
        nav_rows.append((f"{prev_key} / {next_key}", "Switch panel", None))

    # Library-baked hierarchy rows (Esc on children + Enter/Space activation on
    # parents with activatable zones). No mode chip — these are mode-independent.
    nav_rows.extend(
        (display_key, description, None)
        for display_key, description in derive_hierarchy_hints(manager, is_child=is_child)
    )

    # Library-baked mode-exit rows. Each row carries its mode_name as the third
    # tuple element — the renderer attaches the V13 mode chip so the user sees
    # the row applies only while that mode is active.
    nav_rows.extend(derive_mode_exit_hints(manager))

    # Walk action groups, merging shared-section "Navigation" into nav_rows
    # and collecting the rest for downstream emission as their own groups.
    remaining_groups: list[tuple[Optional[str], str, list[KeyAction]]] = []
    for zone_label, group_name, actions in group_actions_by_zone_and_hint_group(manager):
        if zone_label is None and group_name == _BUILTIN_NAV_GROUP:
            # Shared-section Navigation actions: fold into the manager-derived
            # Navigation group so the modal shows one "Navigation" header, not two.
            nav_rows.extend(
                (a.get_display_key(), a.description, mode_context_label(a))
                for a in actions
            )
        else:
            remaining_groups.append((zone_label, group_name, actions))

    # Emit the merged Navigation group (if any rows were collected)
    if nav_rows:
        elements.append(_render_modal_group(_BUILTIN_NAV_GROUP, nav_rows))

    # Emit remaining groups (per-zone, or non-Navigation shared)
    for zone_label, group_name, actions in remaining_groups:
        rows = [
            (a.get_display_key(), a.description, mode_context_label(a))
            for a in actions
        ]
        header = f"{zone_label} — {group_name}" if zone_label else group_name
        elements.append(_render_modal_group(header, rows))

    return elements


def _render_modal_body(
    manager: ZoneManager,                            # primary keyboard zone manager
    include_zone_switch: bool = True,                # include zone-switch hint (single-manager: when multi-zone; multi-manager: per-manager)
    include_navigation: bool = True,                 # DEPRECATED: no-op. Built-in nav row derived from key_mapping now.
    child_managers: Optional[Sequence[ZoneManager]] = None,  # additional managers for hierarchical hint display (each renders as a labeled section)
) -> Div:                                            # modal body with grouped shortcuts
    """Render the modal body with grouped keyboard shortcuts.

    **Single-manager mode** (`child_managers=None`, the common case):
    - Renders one manager's content as a flat list of groups (no section header).
    - Layout: derived "Navigation" group → zone-aware action groups.

    **Multi-manager mode** (`child_managers=[...]`, hierarchical keyboard systems):
    - Renders the primary manager as a labeled section (header = `manager.get_display_label()`),
      followed by each child manager as its own labeled section. Used for
      coordinator-based hierarchies where multiple ZoneManagers cooperate
      (e.g., parent + N children pattern in `cjm-fasthtml-keyboard-navigation`'s
      hierarchy demo). Each manager's content composes via `_render_manager_groups`.
    - Each child manager is rendered with `is_child=True`, which surfaces the
      library-baked Escape→deactivate-parent hint in that child's Navigation
      group (Escape is built into the JS dispatcher's hierarchy handling).

    Layout details (same in both modes):
    - Each group container has `break-inside: avoid-column` so the CSS-columns
      layout never splits a group across columns.
    - Section headers (multi-manager mode) carry `break-after: avoid`
      to keep each header attached to its first group.
    - Mode-restricted actions get a small chip ("split", "default", etc.)
      derived from `mode_context_label(action)`.
    - Per-manager: shared-section actions with `hint_group="Navigation"` fold
      into the manager-derived Navigation group (no duplicate group headers).
    - Library-baked hierarchy + mode-exit rows (Esc deactivate, Enter/Space
      activate, per-mode exit) also fold into the same Navigation group via
      `derive_hierarchy_hints` and `derive_mode_exit_hints`.

    History: an earlier version hardcoded `↑/↓ Navigate items` regardless of
    the manager's actual `key_mapping`. That row was wrong under custom
    mappings (wasd, vim) and was dropped in G4. This version derives the
    nav row from `manager.key_mapping` via `derive_navigation_hints`, which
    is accurate under any KeyMapping configuration. The same derivation
    discipline extends to hierarchy keys (Esc/Enter/Space) and mode-exit keys.
    """
    elements: list[FT] = []

    if child_managers:
        # Multi-manager mode: label the primary manager too, so the hierarchy
        # is visually clear in the rendered modal.
        elements.append(_render_section_header(manager.get_display_label()))

    # Primary manager: is_child=False (it's the root of the hierarchy being documented).
    elements.extend(_render_manager_groups(manager, include_zone_switch=include_zone_switch, is_child=False))

    if child_managers:
        for child in child_managers:
            elements.append(_render_section_header(child.get_display_label()))
            # Children: is_child=True so derive_hierarchy_hints surfaces the
            # Escape→deactivate-parent row in their Navigation group.
            elements.extend(_render_manager_groups(child, include_zone_switch=include_zone_switch, is_child=True))

    # `columns.sm` = CSS column-width: 24rem; browser auto-decides count based
    # on modal's actual rendered width. Short content stays effectively single-
    # column at narrow modal widths; long content (e.g., multi-manager modals)
    # auto-flows into 2-3 columns at wider modal sizes.
    return Div(
        *elements,
        cls=combine_classes(p.t(2), columns.sm),
    )

# %% ../../nbs/components/hints_modal.ipynb #trigger-button
def render_keyboard_hints_trigger(
    modal_id: str = "kb-hints-modal",             # ID of the modal dialog to open
    icon_size: IconSize = icons.ghost_button,     # lucide icon size (V11.R3 ghost-button: "full" — pairs with V1.modal_disclosure at btn-xs)
) -> Button:                                      # ghost button with keyboard icon
    """Render a keyboard icon button that opens the hints modal."""
    return Button(
        lucide_icon("keyboard", size=icon_size),
        cls=combine_classes(buttons.modal_disclosure, btn_modifiers.circle),
        title="Keyboard shortcuts (?)",
        onclick=f"document.getElementById('{modal_id}').showModal();",
        type="button",
    )

# %% ../../nbs/components/hints_modal.ipynb #question-mark-listener
def _render_question_mark_listener(
    modal_id: str,  # ID of the modal dialog to toggle
) -> Script:        # script element with global `?` key listener
    """Render a global `?` key listener that toggles the hints modal.
    
    Uses a named function stored on `window` so that HTMX re-renders
    replace the previous listener instead of accumulating duplicates.
    """
    return Script(f"""
    (function() {{
        // Remove previous listener if it exists (HTMX re-render dedup)
        if (window._kbHintsKeyListener) {{
            document.removeEventListener('keydown', window._kbHintsKeyListener);
        }}
        window._kbHintsKeyListener = function(e) {{
            // Skip if typing in an input, textarea, or contenteditable
            var tag = e.target.tagName;
            if (tag === 'INPUT' || tag === 'TEXTAREA' || e.target.isContentEditable) return;
            if (e.key === '?') {{
                e.preventDefault();
                var m = document.getElementById('{modal_id}');
                if (m) {{
                    if (m.open) {{ m.close(); }}
                    else {{ m.showModal(); }}
                }}
            }}
        }};
        document.addEventListener('keydown', window._kbHintsKeyListener);
    }})();
    """)


# %% ../../nbs/components/hints_modal.ipynb #full-modal
def render_keyboard_hints_modal(
    manager: ZoneManager,                                   # primary keyboard zone manager
    modal_id: str = "kb-hints-modal",                        # HTML ID for the modal dialog
    include_navigation: bool = True,                         # DEPRECATED: no-op kept for backward compat. See _render_modal_body.
    include_zone_switch: bool = True,                        # include zone-switch hint (auto-hidden for single zone)
    enable_question_mark_key: bool = True,                   # add global `?` key listener
    title: str = "Keyboard Shortcuts",                       # modal title text
    child_managers: Optional[Sequence[ZoneManager]] = None,  # child managers for hierarchical hint display (each rendered as a labeled section)
) -> tuple[FT, FT, FT]:                                     # (modal_dialog, trigger_button, question_mark_script)
    """Render a modal-based keyboard shortcut reference.

    Returns three components:
    - `modal_dialog`: The Dialog element (place anywhere in page)
    - `trigger_button`: Small keyboard icon button (place in step header)
    - `question_mark_script`: Global `?` key listener Script (place in page)

    If `enable_question_mark_key` is False, `question_mark_script` is an empty Div.

    **Hierarchical hints** (`child_managers=[...]`): when working with multiple
    ZoneManagers coordinated by `window.kbCoordinator` (parent + N children), pass
    the parent as `manager` and the children as `child_managers`. The modal will
    render each as a labeled section using `manager.get_display_label()` for
    section headers. Set `label` on each ZoneManager for human-readable headers;
    falls back to `system_id` otherwise.

    Modal width ladder (R2 cap + optimal-space response — see
    layout-system.md M1–M6 modes): grows responsively with viewport. Combined
    with `columns.sm` on the body, this gives 1 column at narrow widths,
    2 columns at laptop full-screen (lg breakpoint with max_w._4xl), and
    3 columns at desktop full-screen (2xl breakpoint with max_w._7xl).
    Modal width is an upper bound; DaisyUI's `modal_box` sizes the actual
    modal to its content within that bound, so short content stays compact.
    """
    body = _render_modal_body(
        manager,
        include_zone_switch=include_zone_switch,
        child_managers=child_managers,
    )

    modal_dialog = Dialog(
        Div(
            # Close button (top-right corner)
            Form(
                Button(
                    "✕",
                    cls=combine_classes(
                        buttons.soft_dismissal, btn_modifiers.circle,
                        position.absolute, right._2, top._2,
                    ),
                ),
                method="dialog",
            ),
            # Title
            H3(
                lucide_icon("keyboard", size=icons.section_header, cls=str(m.r(2))),
                title,
                cls=combine_classes(
                    font_size.lg, font_weight.bold,
                    flex_display, items.center,
                ),
            ),
            # Shortcut groups
            body,
            # Footer hint
            Div(
                Span("Press "),
                Kbd("?", cls=combine_classes(kbd_cls, kbd_sz.sm)),
                Span(" to toggle this dialog"),
                cls=combine_classes(
                    font_size.xs, text_tiers.subtle,
                    p.t(3), border.t(), border_dui.base_content.opacity(10),
                    flex_display, items.center, gap(1),
                ),
            ),
            cls=combine_classes(
                modal_box,
                # Responsive max-width ladder per layout-system M1–M6 modes.
                # Values tuned via cross-device retest 2026-05-11: laptop
                # full-screen wants 2-col (lg + max_w._4xl); desktop full-screen
                # wants 3-col (2xl + max_w._7xl). Content-driven actual width:
                # modal shrinks below the cap when content is short.
                max_w.md,           # M1 Pocket base
                max_w.lg.sm,        # M2 Compact (sm 640+)
                max_w._4xl.lg,      # M3 Standard (lg 1024+) — 2-col on laptop
                max_w._7xl._2xl,    # M4+ Spacious (2xl 1536+) — 3-col on desktop
            ),
        ),
        # Backdrop (click outside to close)
        Form(Button("close"), method="dialog", cls=str(modal_backdrop)),
        id=modal_id,
        cls=str(modal),
    )

    trigger = render_keyboard_hints_trigger(modal_id=modal_id)

    question_mark_script = (
        _render_question_mark_listener(modal_id)
        if enable_question_mark_key
        else Div(style="display:none;")
    )

    return modal_dialog, trigger, question_mark_script
