"""High-level API for rendering complete keyboard navigation systems."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/system.ipynb.

# %% ../../nbs/components/system.ipynb #b0895254
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional
from fasthtml.common import Script, Div

from ..core.manager import ZoneManager
from ..js.generators import generate_keyboard_script
from cjm_fasthtml_keyboard_navigation.htmx.inputs import (
    render_hidden_inputs,
    build_include_selector,
    build_all_zones_include_selector
)
from ..htmx.buttons import render_action_buttons
from .hints import render_keyboard_hints

# %% auto #0
__all__ = ['KeyboardSystem', 'render_keyboard_system', 'quick_keyboard_system']

# %% ../../nbs/components/system.ipynb #d1b9ba72
@dataclass
class KeyboardSystem:
    """Container for all keyboard navigation components."""
    script: Script                    # the keyboard navigation JavaScript
    hidden_inputs: Div                # hidden inputs for HTMX
    action_buttons: Div               # hidden action buttons for HTMX
    hints: Optional[Div] = None       # optional keyboard hints UI

    def all_components(self) -> tuple:  # all components as tuple
        """Return all components for easy unpacking into render."""
        components = [self.script, self.hidden_inputs, self.action_buttons]
        if self.hints:
            components.append(self.hints)
        return tuple(components)

# %% ../../nbs/components/system.ipynb #41a45ed5
def _build_auto_include_map(
    manager: ZoneManager,        # the zone manager configuration
    include_state: bool = False  # include state inputs in selector
) -> dict[str, str]:             # action button ID -> include selector
    """Auto-generate include_map based on actions and their zone constraints."""
    include_map = {}
    
    for action in manager.actions:
        if not action.htmx_trigger:
            continue
        
        btn_id = action.htmx_trigger
        
        if action.zone_ids:
            # Action is zone-specific - include only those zones' inputs
            selectors = []
            for zone_id in action.zone_ids:
                zone = manager.get_zone(zone_id)
                if zone:
                    zone_selector = build_include_selector(zone, include_state)
                    if zone_selector:
                        selectors.append(zone_selector)
            include_map[btn_id] = ", ".join(selectors) if selectors else ""
        else:
            # Action applies to all zones - include all zones' inputs
            include_map[btn_id] = build_all_zones_include_selector(manager, include_state)
    
    return include_map


def render_keyboard_system(
    manager: ZoneManager,                         # the zone manager configuration
    url_map: dict[str, str],                      # action button ID -> URL
    target_map: dict[str, str],                   # action button ID -> target selector
    include_map: dict[str, str] | None = None,    # action button ID -> include selector (auto-generated if None)
    swap_map: dict[str, str] | None = None,       # action button ID -> swap value
    vals_map: dict[str, dict] | None = None,      # action button ID -> hx-vals dict
    show_hints: bool = True,                      # render keyboard hints UI
    hints_badge_style: str = "ghost",             # badge style for hints
    include_state_inputs: bool = False            # include state tracking inputs
) -> KeyboardSystem:                              # complete keyboard system
    """Render complete keyboard navigation system."""
    # Generate JavaScript
    script = Script(generate_keyboard_script(manager))
    
    # Generate hidden inputs
    hidden_inputs = render_hidden_inputs(
        manager,
        include_state=include_state_inputs
    )
    
    # Auto-generate include_map if not provided
    if include_map is None:
        include_map = _build_auto_include_map(manager, include_state_inputs)
    
    # Generate action buttons
    action_buttons = render_action_buttons(
        manager,
        url_map=url_map,
        target_map=target_map,
        include_map=include_map,
        swap_map=swap_map,
        vals_map=vals_map
    )
    
    # Generate hints
    hints = None
    if show_hints:
        hints = render_keyboard_hints(
            manager,
            badge_style=hints_badge_style
        )
    
    return KeyboardSystem(
        script=script,
        hidden_inputs=hidden_inputs,
        action_buttons=action_buttons,
        hints=hints
    )

# %% ../../nbs/components/system.ipynb #2bedddcb
def quick_keyboard_system(
    zones: tuple[FocusZone, ...],                # focus zones
    actions: tuple[KeyAction, ...],              # keyboard actions
    url_map: dict[str, str],                     # action URLs
    target_map: dict[str, str],                  # action targets
    **kwargs                                     # additional ZoneManager/render options
) -> KeyboardSystem:                             # complete keyboard system
    """Quick setup for simple keyboard navigation."""
    from cjm_fasthtml_keyboard_navigation.core.focus_zone import FocusZone
    from cjm_fasthtml_keyboard_navigation.core.actions import KeyAction
    
    # Extract manager kwargs
    manager_kwargs = {}
    render_kwargs = {}
    
    manager_keys = {
        'prev_zone_key', 'next_zone_key', 'zone_switch_modifiers',
        'wrap_zones', 'key_mapping', 'initial_zone_id', 'modes',
        'default_mode', 'on_zone_change', 'on_mode_change',
        'on_state_change', 'skip_when_input_focused', 'input_selector',
        'htmx_settle_event', 'expose_state_globally', 'global_state_name',
        'state_hidden_inputs'
    }
    
    render_keys = {
        'include_map', 'swap_map', 'vals_map', 'show_hints',
        'hints_badge_style', 'include_state_inputs'
    }
    
    for key, value in kwargs.items():
        if key in manager_keys:
            manager_kwargs[key] = value
        elif key in render_keys:
            render_kwargs[key] = value
        else:
            # Unknown key - try render_kwargs as fallback
            render_kwargs[key] = value
    
    manager = ZoneManager(
        zones=zones,
        actions=actions,
        **manager_kwargs
    )
    
    return render_keyboard_system(
        manager,
        url_map=url_map,
        target_map=target_map,
        **render_kwargs
    )
