"""Generate hidden HTMX action buttons triggered by keyboard events."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/htmx/buttons.ipynb.

# %% ../../nbs/htmx/buttons.ipynb #15372345
from __future__ import annotations
from fasthtml.common import Button, Div

from ..core.actions import KeyAction
from ..core.manager import ZoneManager

from cjm_fasthtml_tailwind.utilities.layout import display_tw

# %% auto #0
__all__ = ['build_htmx_trigger', 'render_action_button', 'render_action_buttons']

# %% ../../nbs/htmx/buttons.ipynb #54f73115
def build_htmx_trigger(
    key: str,                           # JavaScript key name
    modifiers: frozenset[str] = frozenset(),  # modifier keys
    input_selector: str = "input, textarea, select, [contenteditable]"  # input elements to exclude
) -> str:                               # HTMX trigger expression
    """Build HTMX trigger expression for keyboard event."""
    conditions = []
    
    # Key match - handle special characters
    if key == "'":
        conditions.append('key=="\'"')
    elif key == '"':
        conditions.append("key=='\"'")
    else:
        conditions.append(f"key=='{key}'")
    
    # Modifier checks
    if "shift" in modifiers:
        conditions.append("shiftKey")
    if "ctrl" in modifiers:
        conditions.append("ctrlKey")
    if "alt" in modifiers:
        conditions.append("altKey")
    if "meta" in modifiers:
        conditions.append("metaKey")
    
    # Exclude input elements
    conditions.append(f"!target.matches('{input_selector}')")
    
    return f"keyup[{' && '.join(conditions)}] from:body"

# %% ../../nbs/htmx/buttons.ipynb #82f579e2
def render_action_button(
    action: KeyAction,           # the action configuration
    url: str,                    # POST URL for the action
    target: str,                 # HTMX target selector
    include: str = "",           # hx-include selector
    swap: str = "outerHTML",     # hx-swap value
    input_selector: str = "input, textarea, select, [contenteditable]"  # inputs to exclude
) -> Button | None:              # hidden button or None if not HTMX action
    """Render a hidden HTMX button for a keyboard action."""
    if not action.htmx_trigger:
        return None
    
    trigger_expr = build_htmx_trigger(action.key, action.modifiers, input_selector)
    
    return Button(
        id=action.htmx_trigger,
        hx_post=url,
        hx_target=target,
        hx_swap=swap,
        hx_trigger=trigger_expr,
        hx_include=include if include else None,
        cls=str(display_tw.hidden)
    )

# %% ../../nbs/htmx/buttons.ipynb #aaf80403
def render_action_buttons(
    manager: ZoneManager,              # the zone manager configuration
    url_map: dict[str, str],           # action button ID -> URL
    target_map: dict[str, str],        # action button ID -> target selector
    include_map: dict[str, str] | None = None,  # action button ID -> include selector
    swap_map: dict[str, str] | None = None,     # action button ID -> swap value
    container_id: str = "kb-action-buttons"     # container element ID
) -> Div:                              # container with all action buttons
    """Render all hidden HTMX action buttons for keyboard navigation."""
    include_map = include_map or {}
    swap_map = swap_map or {}
    
    buttons = []
    
    for action in manager.actions:
        if not action.htmx_trigger:
            continue
        
        btn_id = action.htmx_trigger
        url = url_map.get(btn_id, "")
        target = target_map.get(btn_id, "")
        include = include_map.get(btn_id, "")
        swap = swap_map.get(btn_id, "outerHTML")
        
        btn = render_action_button(
            action,
            url=url,
            target=target,
            include=include,
            swap=swap,
            input_selector=manager.input_selector
        )
        
        if btn:
            buttons.append(btn)
    
    return Div(
        *buttons,
        id=container_id,
        cls=str(display_tw.hidden)
    )
