"""Generate hidden HTMX action buttons triggered by keyboard events."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/htmx/buttons.ipynb.

# %% ../../nbs/htmx/buttons.ipynb #e24f2440
from __future__ import annotations
from fasthtml.common import Button, Div

from ..core.actions import KeyAction
from ..core.manager import ZoneManager

from cjm_fasthtml_tailwind.utilities.layout import display_tw

# %% auto #0
__all__ = ['build_htmx_trigger', 'render_action_button', 'render_action_buttons']

# %% ../../nbs/htmx/buttons.ipynb #5c386454
def build_htmx_trigger(
    key: str,                           # JavaScript key name
    modifiers: frozenset[str] = frozenset(),  # modifier keys
    input_selector: str = "input, textarea, select, [contenteditable]"  # input elements to exclude
) -> str:                               # HTMX trigger expression
    """Build HTMX trigger expression for keyboard event."""
    conditions = []
    
    # Key match - handle special characters
    if key == "'":
        conditions.append('key=="\'"')
    elif key == '"':
        conditions.append("key=='\"'")
    else:
        conditions.append(f"key=='{key}'")
    
    # Modifier checks
    if "shift" in modifiers:
        conditions.append("shiftKey")
    if "ctrl" in modifiers:
        conditions.append("ctrlKey")
    if "alt" in modifiers:
        conditions.append("altKey")
    if "meta" in modifiers:
        conditions.append("metaKey")
    
    # Exclude input elements
    conditions.append(f"!target.matches('{input_selector}')")
    
    return f"keyup[{' && '.join(conditions)}] from:body"

# %% ../../nbs/htmx/buttons.ipynb #ba858f12
import json


def render_action_button(
    action: KeyAction,           # the action configuration
    url: str,                    # POST URL for the action
    target: str,                 # HTMX target selector
    include: str = "",           # hx-include selector
    swap: str = "outerHTML",     # hx-swap value
    vals: dict | None = None,    # hx-vals dictionary (JSON values to include in request)
    use_htmx_trigger: bool = False,  # use hx-trigger (False = JS triggerClick only)
    input_selector: str = "input, textarea, select, [contenteditable]"  # inputs to exclude from trigger
) -> Button | None:              # hidden button or None if not HTMX action
    """Render a hidden HTMX button for a keyboard action."""
    if not action.htmx_trigger:
        return None
    
    # Only add hx-trigger if explicitly requested
    # Default is to let JavaScript handle triggering via triggerClick()
    trigger_expr = None
    if use_htmx_trigger:
        trigger_expr = build_htmx_trigger(action.key, action.modifiers, input_selector)
    
    # Convert vals dict to JSON string for hx-vals
    vals_str = json.dumps(vals) if vals else None
    
    return Button(
        id=action.htmx_trigger,
        hx_post=url,
        hx_target=target,
        hx_swap=swap,
        hx_trigger=trigger_expr,
        hx_include=include if include else None,
        hx_vals=vals_str,
        cls=str(display_tw.hidden)
    )

# %% ../../nbs/htmx/buttons.ipynb #721b0c38
def render_action_buttons(
    manager: ZoneManager,                         # the zone manager configuration
    url_map: dict[str, str],                      # action button ID -> URL
    target_map: dict[str, str],                   # action button ID -> target selector
    include_map: dict[str, str] | None = None,    # action button ID -> include selector
    swap_map: dict[str, str] | None = None,       # action button ID -> swap value
    vals_map: dict[str, dict] | None = None,      # action button ID -> hx-vals dict
    use_htmx_triggers: bool = False,              # use hx-trigger (False = JS triggerClick only)
    container_id: str = "kb-action-buttons"       # container element ID
) -> Div:                                         # container with all action buttons
    """Render all hidden HTMX action buttons for keyboard navigation."""
    include_map = include_map or {}
    swap_map = swap_map or {}
    vals_map = vals_map or {}
    
    buttons = []
    
    for action in manager.actions:
        if not action.htmx_trigger:
            continue
        
        btn_id = action.htmx_trigger
        url = url_map.get(btn_id, "")
        target = target_map.get(btn_id, "")
        include = include_map.get(btn_id, "")
        swap = swap_map.get(btn_id, "outerHTML")
        vals = vals_map.get(btn_id, None)
        
        btn = render_action_button(
            action,
            url=url,
            target=target,
            include=include,
            swap=swap,
            vals=vals,
            use_htmx_trigger=use_htmx_triggers,
            input_selector=manager.input_selector
        )
        
        if btn:
            buttons.append(btn)
    
    return Div(
        *buttons,
        id=container_id,
        cls=str(display_tw.hidden)
    )
