"""Generate hidden inputs for HTMX integration with keyboard navigation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/htmx/inputs.ipynb.

# %% ../../nbs/htmx/inputs.ipynb #ff1dc6e3
from __future__ import annotations
from fasthtml.common import Div, Hidden

from ..core.focus_zone import FocusZone
from ..core.manager import ZoneManager

from cjm_fasthtml_tailwind.utilities.layout import display_tw

# %% auto #0
__all__ = ['render_zone_hidden_inputs', 'render_hidden_inputs', 'build_include_selector', 'build_all_zones_include_selector']

# %% ../../nbs/htmx/inputs.ipynb #dfd7ae1f
def render_zone_hidden_inputs(
    zone: FocusZone  # the focus zone configuration
) -> list:           # list of Hidden input components
    """Render hidden inputs for a single zone's data attributes."""
    inputs = []
    for attr in zone.data_attributes:
        input_id = zone.get_hidden_input_id(attr)
        inputs.append(Hidden(id=input_id, name=attr, value=""))
    return inputs

# %% ../../nbs/htmx/inputs.ipynb #9c62450f
def render_hidden_inputs(
    manager: ZoneManager,            # the zone manager configuration
    include_state: bool = False,     # include state tracking inputs
    container_id: str = "kb-hidden-inputs"  # container element ID
) -> Div:                            # container with all hidden inputs
    """Render all hidden inputs for keyboard navigation."""
    inputs = []
    
    # Zone data attribute inputs
    for zone in manager.zones:
        inputs.extend(render_zone_hidden_inputs(zone))
    
    # State tracking inputs (if enabled)
    if include_state or manager.state_hidden_inputs:
        inputs.extend([
            Hidden(id="kb-active-zone", name="kb-active-zone", value=""),
            Hidden(id="kb-current-mode", name="kb-current-mode", value=""),
            Hidden(id="kb-focus-indices", name="kb-focus-indices", value=""),
        ])
    
    return Div(
        *inputs,
        id=container_id,
        cls=str(display_tw.hidden)
    )

# %% ../../nbs/htmx/inputs.ipynb #36f052e8
def build_include_selector(
    zone: FocusZone,              # the zone to include inputs from
    include_state: bool = False   # include state inputs
) -> str:                         # CSS selector for hx-include
    """Build hx-include selector for zone's hidden inputs."""
    selectors = []
    
    for attr in zone.data_attributes:
        input_id = zone.get_hidden_input_id(attr)
        selectors.append(f"#{input_id}")
    
    if include_state:
        selectors.extend([
            "#kb-active-zone",
            "#kb-current-mode"
        ])
    
    return ", ".join(selectors)

# %% ../../nbs/htmx/inputs.ipynb #df0074a7
def build_all_zones_include_selector(
    manager: ZoneManager,         # the zone manager
    include_state: bool = False   # include state inputs
) -> str:                         # CSS selector for all zones
    """Build hx-include selector for all zones' hidden inputs."""
    selectors = []
    
    for zone in manager.zones:
        for attr in zone.data_attributes:
            input_id = zone.get_hidden_input_id(attr)
            selectors.append(f"#{input_id}")
    
    if include_state:
        selectors.extend([
            "#kb-active-zone",
            "#kb-current-mode",
            "#kb-focus-indices"
        ])
    
    return ", ".join(selectors)
